#!/bin/sh

# Usage: merge.sh <output-file> <file1.part> <file2.part> <file3.part> …

INDIR=`dirname $0`
DEST=$1
shift

if [ -z "$HDR" ]; then
    HDR="HDR"
fi

basename=`basename $0`
echo "// DO NOT EDIT THIS FILE - IT WAS AUTOGENERATED BY $basename FROM rules/*.part" >$DEST

# The HDR file contains the headers for each section in the rules file.
# This is fed as stdin to the for loop below.
#
# Wherever the current file is the literal string "HDR", read the next line
# from that file append it to $DEST
# Otherwise, take the filename and append it to $DEST.
#

for partfile in $*; do
  if [ "$partfile" = "$HDR" ] || [ "$partfile" = "HDR" ]; then
    echo >> $DEST;
    read hdr
    echo "$hdr" >> $DEST
  elif test -f $partfile; then
    cat $partfile >> $DEST || exit 1
  else
    cat $INDIR/$partfile >> $DEST || exit 1
  fi
done < $HDR

